import { IMAGES } from './images';

export const PLAYERS_NUM = 4;
export const CHOICES_NUM = 3;
export const DEFAULT_BANS = [19, 40, 42];
export const CIVS = [
    {
        id: 1,
        title: 'America',
        icon: IMAGES.AMERICA,
        picked: true,
    },
    {
        id: 2,
        title: 'Arabia',
        icon: IMAGES.ARABIA,
        picked: true,
    },
    {
        id: 3,
        title: 'Assyria',
        icon: IMAGES.ASSYRIA,
        picked: true,
    },
    {
        id: 4,
        title: 'Austria',
        icon: IMAGES.AUSTRIA,
        picked: true,
    },
    {
        id: 5,
        title: 'Aztecs',
        icon: IMAGES.AZTECS,
        picked: true,
    },
    {
        id: 6,
        title: 'Babylon',
        icon: IMAGES.BABYLON,
        picked: true,
    },
    {
        id: 7,
        title: 'Brazil',
        icon: IMAGES.BRAZIL,
        picked: true,
    },
    {
        id: 8,
        title: 'Byzantium',
        icon: IMAGES.BYZANTIUM,
        picked: true,
    },
    {
        id: 9,
        title: 'Carthage',
        icon: IMAGES.CARTHAGE,
        picked: true,
    },
    {
        id: 10,
        title: 'Celts',
        icon: IMAGES.CELTS,
        picked: true,
    },
    {
        id: 11,
        title: 'China',
        icon: IMAGES.CHINA,
        picked: true,
    },
    {
        id: 12,
        title: 'Denmark',
        icon: IMAGES.DENMARK,
        picked: true,
    },
    {
        id: 13,
        title: 'Egypt',
        icon: IMAGES.EGYPT,
        picked: true,
    },
    {
        id: 14,
        title: 'England',
        icon: IMAGES.ENGLAND,
        picked: true,
    },
    {
        id: 15,
        title: 'Ethiopia',
        icon: IMAGES.ETHIOPIA,
        picked: true,
    },
    {
        id: 16,
        title: 'France',
        icon: IMAGES.FRANCE,
        picked: true,
    },
    {
        id: 17,
        title: 'Germany',
        icon: IMAGES.GERMANY,
        picked: true,
    },
    {
        id: 18,
        title: 'Greece',
        icon: IMAGES.GREECE,
        picked: true,
    },
    {
        id: 19,
        title: 'Huns',
        icon: IMAGES.HUNS,
        picked: true,
    },
    {
        id: 20,
        title: 'Inca',
        icon: IMAGES.INCA,
        picked: true,
    },
    {
        id: 21,
        title: 'India',
        icon: IMAGES.INDIA,
        picked: true,
    },
    {
        id: 22,
        title: 'Indonesia',
        icon: IMAGES.INDONESIA,
        picked: true,
    },
    {
        id: 23,
        title: 'Iroquois',
        icon: IMAGES.IROQUOIS,
        picked: true,
    },
    {
        id: 24,
        title: 'Japan',
        icon: IMAGES.JAPAN,
        picked: true,
    },
    {
        id: 25,
        title: 'Korea',
        icon: IMAGES.KOREA,
        picked: true,
    },
    {
        id: 26,
        title: 'Maya',
        icon: IMAGES.MAYA,
        picked: true,
    },
    {
        id: 27,
        title: 'Mongolia',
        icon: IMAGES.MONGOLIA,
        picked: true,
    },
    {
        id: 28,
        title: 'Morocco',
        icon: IMAGES.MOROCCO,
        picked: true,
    },
    {
        id: 29,
        title: 'Netherlands',
        icon: IMAGES.NETHERLANDS,
        picked: true,
    },
    {
        id: 30,
        title: 'Ottomans',
        icon: IMAGES.OTTOMANS,
        picked: true,
    },
    {
        id: 31,
        title: 'Persia',
        icon: IMAGES.PERSIA,
        picked: true,
    },
    {
        id: 32,
        title: 'Poland',
        icon: IMAGES.POLAND,
        picked: true,
    },
    {
        id: 33,
        title: 'Polynesia',
        icon: IMAGES.POLYNESIA,
        picked: true,
    },
    {
        id: 34,
        title: 'Portugal',
        icon: IMAGES.PORTUGAL,
        picked: true,
    },
    {
        id: 35,
        title: 'Rome',
        icon: IMAGES.ROME,
        picked: true,
    },
    {
        id: 36,
        title: 'Russia',
        icon: IMAGES.RUSSIA,
        picked: true,
    },
    {
        id: 37,
        title: 'Shoshone',
        icon: IMAGES.SHOSHONE,
        picked: true,
    },
    {
        id: 38,
        title: 'Siam',
        icon: IMAGES.SIAM,
        picked: true,
    },
    {
        id: 39,
        title: 'Songhai',
        icon: IMAGES.SONGHAI,
        picked: true,
    },
    {
        id: 40,
        title: 'Spain',
        icon: IMAGES.SPAIN,
        picked: true,
    },
    {
        id: 41,
        title: 'Sweden',
        icon: IMAGES.SWEDEN,
        picked: true,
    },
    {
        id: 42,
        title: 'Venice',
        icon: IMAGES.VENICE,
        picked: true,
    },
    {
        id: 43,
        title: 'Zulus',
        icon: IMAGES.ZULUS,
        picked: true,
    },
];
