const URL_PREFIX = 'civ-randomizer-v2/images/';

export const CIVS = [
    {
        id: 1,
        title: 'America',
        icon: URL_PREFIX + 'america.png',
        picked: false,
    },
    {
        id: 2,
        title: 'Arabia',
        icon: URL_PREFIX + 'arabia.png',
        picked: false,
    },
    {
        id: 3,
        title: 'Assyria',
        icon: URL_PREFIX + 'assyria.png',
        picked: false,
    },
    {
        id: 4,
        title: 'Austria',
        icon: URL_PREFIX + 'austria.png',
        picked: false,
    },
    {
        id: 5,
        title: 'Aztecs',
        icon: URL_PREFIX + 'aztecs.png',
        picked: false,
    },
    {
        id: 6,
        title: 'Babylon',
        icon: URL_PREFIX + 'babylon.png',
        picked: false,
    },
    {
        id: 7,
        title: 'Brazil',
        icon: URL_PREFIX + 'brazil.png',
        picked: false,
    },
    {
        id: 8,
        title: 'Byzantium',
        icon: URL_PREFIX + 'byzantium.png',
        picked: false,
    },
    {
        id: 9,
        title: 'Carthage',
        icon: URL_PREFIX + 'carthage.png',
        picked: false,
    },
    {
        id: 10,
        title: 'Celts',
        icon: URL_PREFIX + 'celts.png',
        picked: false,
    },
    {
        id: 11,
        title: 'China',
        icon: URL_PREFIX + 'china.png',
        picked: false,
    },
    {
        id: 12,
        title: 'Denmark',
        icon: URL_PREFIX + 'denmark.png',
        picked: false,
    },
    {
        id: 13,
        title: 'Egypt',
        icon: URL_PREFIX + 'egypt.png',
        picked: false,
    },
    {
        id: 14,
        title: 'England',
        icon: URL_PREFIX + 'england.png',
        picked: false,
    },
    {
        id: 15,
        title: 'Ethiopia',
        icon: URL_PREFIX + 'ethiopia.png',
        picked: false,
    },
    {
        id: 16,
        title: 'France',
        icon: URL_PREFIX + 'france.png',
        picked: false,
    },
    {
        id: 17,
        title: 'Germany',
        icon: URL_PREFIX + 'germany.png',
        picked: false,
    },
    {
        id: 18,
        title: 'Greece',
        icon: URL_PREFIX + 'greece.png',
        picked: false,
    },
    {
        id: 19,
        title: 'Huns',
        icon: URL_PREFIX + 'huns.png',
        picked: false,
    },
    {
        id: 20,
        title: 'Inca',
        icon: URL_PREFIX + 'inca.png',
        picked: false,
    },
    {
        id: 21,
        title: 'India',
        icon: URL_PREFIX + 'india.png',
        picked: false,
    },
    {
        id: 22,
        title: 'Indonesia',
        icon: URL_PREFIX + 'indonesia.png',
        picked: false,
    },
    {
        id: 23,
        title: 'Iroquois',
        icon: URL_PREFIX + 'iroquois.png',
        picked: false,
    },
    {
        id: 24,
        title: 'Japan',
        icon: URL_PREFIX + 'japan.png',
        picked: false,
    },
    {
        id: 25,
        title: 'Korea',
        icon: URL_PREFIX + 'korea.png',
        picked: false,
    },
    {
        id: 26,
        title: 'Maya',
        icon: URL_PREFIX + 'maya.png',
        picked: false,
    },
    {
        id: 27,
        title: 'Mongolia',
        icon: URL_PREFIX + 'mongolia.png',
        picked: false,
    },
    {
        id: 28,
        title: 'Morocco',
        icon: URL_PREFIX + 'morocco.png',
        picked: false,
    },
    {
        id: 29,
        title: 'Netherlands',
        icon: URL_PREFIX + 'netherlands.png',
        picked: false,
    },
    {
        id: 30,
        title: 'Ottomans',
        icon: URL_PREFIX + 'ottomans.png',
        picked: false,
    },
    {
        id: 31,
        title: 'Persia',
        icon: URL_PREFIX + 'persia.png',
        picked: false,
    },
    {
        id: 32,
        title: 'Poland',
        icon: URL_PREFIX + 'poland.png',
        picked: false,
    },
    {
        id: 33,
        title: 'Polynesia',
        icon: URL_PREFIX + 'polynesia.png',
        picked: false,
    },
    {
        id: 34,
        title: 'Portugal',
        icon: URL_PREFIX + 'portugal.png',
        picked: false,
    },
    {
        id: 35,
        title: 'Rome',
        icon: URL_PREFIX + 'rome.png',
        picked: false,
    },
    {
        id: 36,
        title: 'Russia',
        icon: URL_PREFIX + 'russia.png',
        picked: false,
    },
    {
        id: 37,
        title: 'Shoshone',
        icon: URL_PREFIX + 'shoshone.png',
        picked: false,
    },
    {
        id: 38,
        title: 'Siam',
        icon: URL_PREFIX + 'siam.png',
        picked: false,
    },
    {
        id: 39,
        title: 'Songhai',
        icon: URL_PREFIX + 'songhai.png',
        picked: false,
    },
    {
        id: 40,
        title: 'Spain',
        icon: URL_PREFIX + 'spain.png',
        picked: false,
    },
    {
        id: 41,
        title: 'Sweden',
        icon: URL_PREFIX + 'sweden.png',
        picked: false,
    },
    {
        id: 42,
        title: 'Venice',
        icon: URL_PREFIX + 'venice.png',
        picked: false,
    },
    {
        id: 43,
        title: 'Zulus',
        icon: URL_PREFIX + 'zulus.png',
        picked: false,
    },
];
