export const CIVS = [
    {
        id: 1,
        title: 'America',
        icon: '/images/america.png',
        picked: false,
    },
    {
        id: 2,
        title: 'Arabia',
        icon: '/images/arabia.png',
        picked: false,
    },
    {
        id: 3,
        title: 'Assyria',
        icon: '/images/assyria.png',
        picked: false,
    },
    {
        id: 4,
        title: 'Austria',
        icon: '/images/austria.png',
        picked: false,
    },
    {
        id: 5,
        title: 'Aztecs',
        icon: '/images/aztecs.png',
        picked: false,
    },
    {
        id: 6,
        title: 'Babylon',
        icon: '/images/babylon.png',
        picked: false,
    },
    {
        id: 7,
        title: 'Brazil',
        icon: '/images/brazil.png',
        picked: false,
    },
    {
        id: 8,
        title: 'Byzantium',
        icon: '/images/byzantium.png',
        picked: false,
    },
    {
        id: 9,
        title: 'Carthage',
        icon: '/images/carthage.png',
        picked: false,
    },
    {
        id: 10,
        title: 'Celts',
        icon: '/images/celts.png',
        picked: false,
    },
    {
        id: 11,
        title: 'China',
        icon: '/images/china.png',
        picked: false,
    },
    {
        id: 12,
        title: 'Denmark',
        icon: '/images/denmark.png',
        picked: false,
    },
    {
        id: 13,
        title: 'Egypt',
        icon: '/images/egypt.png',
        picked: false,
    },
    {
        id: 14,
        title: 'England',
        icon: '/images/england.png',
        picked: false,
    },
    {
        id: 15,
        title: 'Ethiopia',
        icon: '/images/ethiopia.png',
        picked: false,
    },
    {
        id: 16,
        title: 'France',
        icon: '/images/france.png',
        picked: false,
    },
    {
        id: 17,
        title: 'Germany',
        icon: '/images/germany.png',
        picked: false,
    },
    {
        id: 18,
        title: 'Greece',
        icon: '/images/greece.png',
        picked: false,
    },
    {
        id: 19,
        title: 'Huns',
        icon: '/images/huns.png',
        picked: false,
    },
    {
        id: 20,
        title: 'Inca',
        icon: '/images/inca.png',
        picked: false,
    },
    {
        id: 21,
        title: 'India',
        icon: '/images/india.png',
        picked: false,
    },
    {
        id: 22,
        title: 'Indonesia',
        icon: '/images/indonesia.png',
        picked: false,
    },
    {
        id: 23,
        title: 'Iroquois',
        icon: '/images/iroquois.png',
        picked: false,
    },
    {
        id: 24,
        title: 'Japan',
        icon: '/images/japan.png',
        picked: false,
    },
    {
        id: 25,
        title: 'Korea',
        icon: '/images/korea.png',
        picked: false,
    },
    {
        id: 26,
        title: 'Maya',
        icon: '/images/maya.png',
        picked: false,
    },
    {
        id: 27,
        title: 'Mongolia',
        icon: '/images/mongolia.png',
        picked: false,
    },
    {
        id: 28,
        title: 'Morocco',
        icon: '/images/morocco.png',
        picked: false,
    },
    {
        id: 29,
        title: 'Netherlands',
        icon: '/images/netherlands.png',
        picked: false,
    },
    {
        id: 30,
        title: 'Ottomans',
        icon: '/images/ottomans.png',
        picked: false,
    },
    {
        id: 31,
        title: 'Persia',
        icon: '/images/persia.png',
        picked: false,
    },
    {
        id: 32,
        title: 'Poland',
        icon: '/images/poland.png',
        picked: false,
    },
    {
        id: 33,
        title: 'Polynesia',
        icon: '/images/polynesia.png',
        picked: false,
    },
    {
        id: 34,
        title: 'Portugal',
        icon: '/images/portugal.png',
        picked: false,
    },
    {
        id: 35,
        title: 'Rome',
        icon: '/images/rome.png',
        picked: false,
    },
    {
        id: 36,
        title: 'Russia',
        icon: '/images/russia.png',
        picked: false,
    },
    {
        id: 37,
        title: 'Shoshone',
        icon: '/images/shoshone.png',
        picked: false,
    },
    {
        id: 38,
        title: 'Siam',
        icon: '/images/siam.png',
        picked: false,
    },
    {
        id: 39,
        title: 'Songhai',
        icon: '/images/songhai.png',
        picked: false,
    },
    {
        id: 40,
        title: 'Spain',
        icon: '/images/spain.png',
        picked: false,
    },
    {
        id: 41,
        title: 'Sweden',
        icon: '/images/sweden.png',
        picked: false,
    },
    {
        id: 42,
        title: 'Venice',
        icon: '/images/venice.png',
        picked: false,
    },
    {
        id: 43,
        title: 'Zulus',
        icon: '/images/zulus.png',
        picked: false,
    },
];
